# Generated by Django 5.0.3 on 2024-05-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_EMTA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='profileVerification',
            field=models.CharField(choices=[('Under Process', 'Under Process'), ('Verified', 'Verified'), ('Rejected(Upload Details Again)', 'Rejected(Upload Details Again)')], default='Under Process', max_length=50),
        ),
    ]
